# Generated by Django 4.2.10 on 2026-03-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='openid',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='微信小程序openid'),
        ),
    ]
