# Generated by Django 4.2.10 on 2026-02-11 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds', models.IntegerField(blank=True, null=True, verbose_name='局数（无限制则为空）')),
                ('match_mode', models.CharField(choices=[('zhongba', '中八'), ('zhuifen', '追分')], default='zhongba', max_length=10, verbose_name='比赛模式')),
                ('is_handicap', models.BooleanField(default=False, verbose_name='是否让球')),
                ('handicap_num', models.IntegerField(blank=True, null=True, verbose_name='让球数')),
                ('status', models.CharField(choices=[('pending', '待开始'), ('ongoing', '比赛中'), ('ended', '比赛结束')], default='pending', max_length=10, verbose_name='比赛状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_matches', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('handicap_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handicap_matches', to=settings.AUTH_USER_MODEL, verbose_name='让球者')),
                ('handicapped_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handicapped_matches', to=settings.AUTH_USER_MODEL, verbose_name='被让球者')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_matches', to=settings.AUTH_USER_MODEL, verbose_name='对手')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to=settings.AUTH_USER_MODEL, verbose_name='胜利者')),
            ],
            options={
                'verbose_name': '比赛',
                'verbose_name_plural': '比赛',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('add', '加分'), ('subtract', '减分'), ('system_end', '系统结束'), ('manual_end', '手动结束')], max_length=10, verbose_name='操作类型')),
                ('operation_log', models.CharField(max_length=200, verbose_name='操作日志')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_logs', to='match.match', verbose_name='关联比赛')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operated_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '记分日志',
                'verbose_name_plural': '记分日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_score', models.IntegerField(default=0, verbose_name='选手1分数')),
                ('player2_score', models.IntegerField(default=0, verbose_name='选手2分数')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_score', to='match.match', verbose_name='关联比赛')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_scores', to=settings.AUTH_USER_MODEL, verbose_name='选手1（创建人）')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_scores', to=settings.AUTH_USER_MODEL, verbose_name='选手2（对手）')),
            ],
            options={
                'verbose_name': '比赛记分',
                'verbose_name_plural': '比赛记分',
            },
        ),
    ]
